version: '3'

services:
  react-ui:
    container_name: react-ui
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/src'
      # - '/src/node_modules'
    # command: yarn start
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
